language: android

env:
  global:
    MALLOC_ARENA_MAX=2
    
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb shell input keyevent 82 &

script:
  ./gradlew checkstyle build connectedAndroidTest --stacktrace